### ISSUE TITLE
Running this deleted the rom and the folder it was in

### ISSUE THREAD

**Issue by Wambosa** [evandixon/DotNet3dsToolkit#19]
running this app deleted my rom file because it was in the same folder as the drop location

**Comment by evandixon** [comment]
I'm unable to reproduce this, but I've added a check to prevent this in a3f0e98e786ffc9aec93cf72e4931fe0561020e9. It'll be a while before a full release is out, but you can use the latest version by downloading it from [Team City](https://teamcity.projectpokemon.org/repository/download/RomEditors_Net3dsToolkit_BuildWindows/28567:id/Dot%20Net%203DS%20Toolkit%20Build%2053.zip) (log in as a guest when prompted).
